export declare class WafArkanoid {
    paddlePosition: number;
    width: number;
    height: number;
    activateKeyboardControls: boolean;
    activateMouseControls: boolean;
    activateFaceControls: boolean;
    private isPaused;
    private isGameOver;
    private model;
    private faceDetectLimiterActive;
    private akElt;
    private akCanvasCtx;
    private configURL;
    private config;
    private player;
    private worker;
    render(): any[];
    paddlePositionHandler(newValue: any): void;
    componentDidLoad(): Promise<void>;
    updateKeyboardCtrlState(isActive: boolean): void;
    updateMouseCtrlState(isActive: boolean): void;
    updateFaceCtrlState(isActive: boolean): void;
    componentDidUnload(): void;
    private drawLoop;
    private update;
    private paddleTweener;
    private drawModel;
    private paddlePositionConverter;
    private elapsedTime;
    private generateBricksModel;
    private generatePaddleModel;
    private generateBallModel;
    private gameInitModel;
    private setupControls;
    pause(): void;
    private gameover;
    start(): void;
    playSound(soundKey: String): void;
}
