export declare class WafArkanoid {
    paddlePosition: number;
    width: number;
    height: number;
    activateKeyboardControls: boolean;
    activateMouseControls: boolean;
    activateFaceControls: boolean;
    private isPaused;
    private isGameOver;
    private model;
    private faceDetectLimiterActive;
    private akElt;
    private akCanvasCtx;
    private configURL;
    private config;
    private player;
    private worker;
    render(): any[];
    paddlePositionHandler(newValue: any): void;
    componentDidLoad(): Promise<void>;
    updateKeyboardCtrlState(isActive: boolean): void;
    updateMouseCtrlState(isActive: boolean): void;
    updateFaceCtrlState(isActive: boolean): void;
    componentDidUnload(): void;
    private drawLoop(DHRTimeStamp?);
    private update(dt);
    private paddleTweener(dt, paddle);
    private drawModel(model);
    private paddlePositionConverter(ratio);
    private elapsedTime(DHRTimeStamp);
    private generateBricksModel(configBrick, levelBluePrint, canvasWidth);
    private generatePaddleModel(configPaddle, canvasHeight);
    private generateBallModel(configBall, paddleModel);
    private gameInitModel();
    private setupControls(controlType, destroy?);
    pause(): void;
    private gameover();
    start(): void;
    playSound(soundKey: String): void;
}
