language: node_js
node_js:
   - “7”

branches:
   only:
      - master

cache:
  directories:
    - node_modules

before_install:
  - npm prune

before_script:
   - npm install -g firebase-tools

script:
   - npm run build

after_success:
   - firebase deploy --token $FIREBASE_TOKEN

env:
  global:
    - NODE_ENV=production
