language: node_js
node_js:
   - "7"

branches:
   only:
      - master
      - develop

cache:
  directories:
    - node_modules

before_install:
  - npm prune

before_script:
   - npm install -g firebase-tools

script:
   - if [ "$TRAVIS_BRANCH" == "master" ]; then npm run build; fi
   - if [ "$TRAVIS_BRANCH" == "develop" ]; then npm run pprod-build; fi

after_success:
   - if [ "$TRAVIS_BRANCH" == "master" ]; then firebase deploy --token $FIREBASE_TOKEN --project production; fi
   - if [ "$TRAVIS_BRANCH" == "develop" ]; then firebase deploy --token $FIREBASE_TOKEN --project pprod; fi
